[10.0] [FWD] [MIG] hr_timesheet_no_closed_project_task
OCA/timesheet pull request #101
Opened 2017-05-30 08:26 UTC by ThomasBinsfeld

Forward port from 8.0 (#70)
Waiting #93

2017-10-02 08:27 UTC, ThomasBinsfeld commented
Rebased on 10.0, ready for reviews

2017-10-03 07:57 UTC, benwillig requested changes

2017-10-03 07:57 UTC, benwillig commented on hr_timesheet_no_closed_project_task/static/src/js/timesheet.js
> +            self.task_m2o.node.attrs.domain.push(['stage_id.closed', '=', false]);
This line is duplicated. Maybe you could create a method which does that.

2017-10-03 07:59 UTC, benwillig commented on hr_timesheet_no_closed_project_task/static/src/js/timesheet.js
> +            self.task_m2o.node.attrs.domain.push(['stage_id.closed', '=', false]);
And why declaring ```var self = this``` if you still use ```this```?

2017-10-03 08:48 UTC, gurneyalex approved these changes

2018-02-19 15:01 UTC, benwillig approved these changes

2018-02-22 05:59 UTC, feketemihai approved these changes

2018-02-22 05:59 UTC, merged