[10.0][MIG] hr_timesheet_activity_begin_end
OCA/timesheet pull request #104
Opened 2017-06-14 10:40 UTC by luismontalba

Timesheet Activities - Begin/End Hours
-------------------------------------------------
Adds starting and ending hours fields on the timesheet activities.
The new fields are displayed on the timesheet activities.

cc @Tecnativa

2017-06-19 00:31 UTC, pedrobaeza requested changes

2017-06-19 00:31 UTC, pedrobaeza commented on hr_timesheet_activity_begin_end/README.rst
>  Known issues / Roadmap
Remove this section as it's empty

2017-06-19 00:31 UTC, pedrobaeza commented on hr_timesheet_activity_begin_end/__manifest__.py
> +# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html
Add your copyright

2017-06-19 00:31 UTC, pedrobaeza commented on hr_timesheet_activity_begin_end/__manifest__.py
>   'author': 'Camptocamp,Odoo Community Association (OCA)',
Add Tecnativa

2017-06-19 00:31 UTC, pedrobaeza commented on hr_timesheet_activity_begin_end/models/account_analytic_line.py
> +# Copyright 2015 Camptocamp SA - Guewen Baconnier
Add your copyright

2017-06-19 00:31 UTC, pedrobaeza commented on hr_timesheet_activity_begin_end/views/hr_analytic_timesheet.xml
> +  <!--<record id="hr_timesheet_line_form" model="ir.ui.view">-->
Remove commented views

2017-06-19 00:31 UTC, pedrobaeza commented on hr_timesheet_activity_begin_end/views/hr_timesheet_sheet.xml
> +  <record id="hr_timesheet_sheet_form" model="ir.ui.view">
You are not using 4 spaces indent here

2017-06-19 08:12 UTC, luismontalba commented
Changes proposed done (commit whit changes squashed)

2017-06-20 15:58 UTC, pedrobaeza approved these changes

2017-08-08 13:44 UTC, pedrobaeza commented
@chienandalu please review

2017-08-10 16:09 UTC, luismontalba commented
After make a rebase apparently runbot image is built, but the link to data base seems to be broken:

![enlace](https://user-images.githubusercontent.com/5930419/29180060-d29ddac0-7df6-11e7-87e5-9b8cf85df943.png)

2017-08-10 17:01 UTC, pedrobaeza commented
Sometimes runbot doesn't complete the request, but just refresh and it's everything working.

2017-08-11 14:23 UTC, chienandalu approved these changes
:+1:

2017-08-14 10:16 UTC, merged