.travis.yml: Put it up to date
OCA/timesheet pull request #109
Opened 2017-06-27 14:51 UTC by chienandalu

cc @Tecnativa

2017-06-27 19:01 UTC, pedrobaeza requested changes

2017-06-27 19:01 UTC, pedrobaeza commented on .travis.yml
> -virtualenv:
Don't remove this

2017-06-28 06:24 UTC, chienandalu commented
@pedrobaeza done

2017-06-28 07:42 UTC, pedrobaeza approved these changes

2017-06-28 07:42 UTC, merged