[10.0] [ADD] hr_timesheet_sheet_period
OCA/timesheet pull request #111
Opened 2017-07-17 12:44 UTC by nikul-serpentcs

HR Timesheet Sheet based on Payroll Period
==========================================

This module allows to create timesheets with start and end dates matching with the
payroll period of the schedule pay that is specified in the contract of the 
employee or if not then will match the nearest payroll period.

2017-07-17 12:45 UTC, nikul-serpentcs commented
@aheficent Could you please review code.

2017-07-18 08:11 UTC, lreficent commented
Depens on https://github.com/OCA/hr/pull/352

2017-07-18 08:11 UTC, lreficent commented
Can you please attend travis? @nikul-serpentcs

2017-10-27 11:30 UTC, nikul-serpentcs commented
@lreficent Because depends on module `hr_period`, is not available.

2017-11-29 12:06 UTC, AaronHForgeFlow requested changes

2017-11-29 12:06 UTC, aheficent commented on hr_timesheet_sheet_period/models/hr_timesheet_sheet.py
> +            return period.date_stop
The field in the date_range module and in the hr_period module is `date_end`

2017-11-29 12:06 UTC, aheficent commented on hr_timesheet_sheet_period/models/hr_timesheet_sheet.py
> +                         ('date_stop', '>=', date_today)]
date_end

2017-11-30 04:30 UTC, nikul-serpentcs commented
@aheficent I did rename a fields, Could you please review code.

2017-12-14 17:01 UTC, aheficent commented
Hi @nikul-serpentcs  Thank you for attending the commits. Can you review and merge this? https://github.com/nikul-serpentcs/hr-timesheet/pull/1

2018-03-12 11:23 UTC, aheficent commented
Hi @nikul-serpentcs I'll take care of this PR here: https://github.com/OCA/hr-timesheet/pull/123 Feel free to close this

2018-03-12 11:25 UTC, closed without merging