[12.0][FIX] hr_timesheet_sheet: who approves timesheets should be the manager
OCA/timesheet pull request #160
Opened 2018-12-17 12:08 UTC by mreficent

Forward port of https://github.com/OCA/hr-timesheet/pull/159.

2018-12-17 12:27 UTC, alexey-pelykh commented
@mreficent please check https://github.com/OCA/hr-timesheet/issues/145#issuecomment-447827033

2018-12-17 12:41 UTC, alexey-pelykh requested changes
It is expected for reviewer to be employee's manager (`parent_id` of `hr.employee` model), which does not mean that the user has to be in `hr_timesheet.group_hr_timesheet_user` group.

2018-12-20 16:54 UTC, alexey-pelykh approved these changes

2018-12-24 08:05 UTC, alexey-pelykh commented
@lreficent since you've reviewed #159 - please review this one as well, if you don't mind

2019-01-28 14:47 UTC, LoisRForgeFlow approved these changes

2019-01-28 15:04 UTC, merged