[WIP][ADD] hr_timesheet_report: generate various reports from Task Logs
OCA/timesheet pull request #161
Opened 2018-12-18 01:56 UTC by alexey-pelykh

2018-12-19 07:21 UTC, alexey-pelykh commented
@aheficent @pedrobaeza I'd like to request your early opinion on this module. As of now pie charts are not in place and XLSX export is not implemented (due to https://github.com/OCA/reporting-engine/pull/248)

2018-12-19 20:23 UTC, alexey-pelykh commented
For the record: https://github.com/odoo/odoo/blob/9b6073c3ea6264f59fb11e6f797f4fff200c3d5d/odoo/addons/base/models/qweb.py#L1293 is why dynamic field name resolution like
```
<span t-field="record[variable]"/>
```
can not be used

2018-12-21 06:12 UTC, alexey-pelykh commented
Implemented XLSX export, so this is out of WIP status

2018-12-21 08:22 UTC, AaronHForgeFlow approved these changes
:+1: Awesome module! Thanks. Tested on runbot and love it.

2018-12-22 21:10 UTC, alexey-pelykh commented
Going to add one more report, the utilization one in a day or two

2018-12-24 11:21 UTC, alexey-pelykh commented
@lreficent @mreficent if you don't mind, please review this PR as well

2019-02-13 14:07 UTC, alexey-pelykh commented
@tarteo would you be interested in reviewing this module?

2019-03-21 09:51 UTC, alexey-pelykh commented
@astirpe any interest in this module?

2019-03-22 15:02 UTC, astirpe requested changes
Just installed the module and launched the report on the following lines:

```

  | 03/22/2019 | Pieter Parker | Website | Data Import/Export Plugin |   | 02:00
  | 03/17/2019 | Pieter Parker | Delivery and maintenance | Research & Development |   | 01:00
  | 03/17/2019 | Pieter Parker | Integration and system testing | Research & Development |   | 01:00
  | 03/17/2019 | Pieter Parker | Coding and module testing | Research & Development |   | 03:00
  | 03/17/2019 | Pieter Parker | Design and specification | Research & Development |   | 01:00
  | 03/17/2019 | Pieter Parker | Requirements analysis and specification | Research & Development |   | 02:00
```

I got this:


```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/fields.py", line 940, in __get__
    value = record.env.cache.get(record, self)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/oca/hr_timesheet_report/wizards/hr_timesheet_report_wizard.py", line 132, in action_export_html
    action = self._generate_report('qweb-html')
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/oca/hr_timesheet_report/wizards/hr_timesheet_report_wizard.py", line 157, in _generate_report
    self._collect_report_values()
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/models.py", line 3394, in create
    record = self.browse(self._create(old_vals))
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/models.py", line 3551, in _create
    self.recompute()
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/models.py", line 4931, in recompute
    vals = {n: rec[n] for n in ns}
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/models.py", line 4931, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/models.py", line 4785, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/fields.py", line 944, in __get__
    self.determine_value(record)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/fields.py", line 1031, in determine_value
    self.compute_value(recs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/fields.py", line 1011, in compute_value
    self._compute_value(records)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/fields.py", line 1002, in _compute_value
    getattr(records, self.compute)()
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/oca/hr_timesheet_report/report/hr_timesheet_report.py", line 119, in _compute_group_ids
    lazy=False,
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/models.py", line 1909, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/models.py", line 1944, in _read_group_raw
    assert gb in fields, "Fields in 'groupby' must appear in the list of fields to read (perhaps it's missing in the list view?)"
AssertionError: Fields in 'groupby' must appear in the list of fields to read (perhaps it's missing in the list view?)
```

2019-03-22 15:02 UTC, astirpe commented on hr_timesheet_report/readme/USAGE.rst
> +#. Go to *Timesheets > My Timesheets* or *Timesheets > All timesheets*.
You need an empty line before the list, otherwise the file doesn't look good. See [how it looks now](https://github.com/OCA/hr-timesheet/blob/948860117e72fa9ea20628bbdc8c1ddae7bbc86f/hr_timesheet_report/README.rst#id1).

2019-03-23 08:24 UTC, alexey-pelykh commented
@astirpe you've tested on v11 or v12?

2019-03-23 08:27 UTC, alexey-pelykh commented on hr_timesheet_report/readme/USAGE.rst
> +#. Go to *Timesheets > My Timesheets* or *Timesheets > All timesheets*.
Thanks, fixed!

2019-03-23 09:11 UTC, astirpe commented
Yeah I tried it on a v11 :see_no_evil: sorry!

2019-03-23 09:33 UTC, alexey-pelykh commented
@astirpe no worries, I've adjusted the code so maybe it's already compatible with v11, yet it would be great if you'd try in on a runbot :)

2019-06-06 08:24 UTC, pedrobaeza commented
Shouldn't this can be a more generic "Reporting engine" with grouping and columns adding a new field model, populating fields to group and show from it? The title of the report can be also configurable.

2019-06-06 08:28 UTC, alexey-pelykh commented
@pedrobaeza I'm not sure I follow - except for making title of the report configurable, what other making-more-generic things should be done?

2019-06-06 08:30 UTC, pedrobaeza commented
The model, for having a generic reporting engine in any document

2019-06-06 10:24 UTC, alexey-pelykh commented
@pedrobaeza like extract base of this module from timesheet-specific things and put it into the `reporting-engine`?

2019-06-06 10:31 UTC, pedrobaeza commented
Exactly!

2019-06-06 11:07 UTC, alexey-pelykh commented
I guess I could use some extra hands for this

2020-06-24 07:34 UTC, alexey-pelykh commented
@pedrobaeza I’ve considered splitting this as proposed yet I haven’t found enough justification where else it can be used. Thus I propose to proceed as is, and possibly split in future versions

2020-06-24 12:41 UTC, pedrobaeza commented
OK, as you considered

2020-06-24 12:44 UTC, alexey-pelykh commented
@pedrobaeza thanks! Would it be possible to get a review from you?

2020-06-24 12:46 UTC, pedrobaeza commented
Sorry, but that's too much from my part.

2020-06-26 05:47 UTC, alexey-pelykh commented
@Saran440 maybe you'd be interested in reviewing this?

2020-06-26 10:42 UTC, Saran440 commented
@alexey-pelykh Good module!
Functional Test

1. If Details Fields is empty, It will default Date and Description.
should it be show Hour(s) only or Validationerror when Details Fields is empty?
![Selection_006](https://user-images.githubusercontent.com/20896369/85848283-182ff500-b7d3-11ea-962b-68339a4cd06b.png)
![Selection_007](https://user-images.githubusercontent.com/20896369/85848451-5af1cd00-b7d3-11ea-8735-5431a2b95524.png)


2. This report can show state in task? It useful in report.

2020-06-26 13:53 UTC, alexey-pelykh commented
@Saran440 thanks for your review! As for empty details fields - that's odd, by default Date and Description should be listed there. As for adding task status - could be, yes, but I think that should be an extra module to extend this one.

2020-06-26 14:28 UTC, alexey-pelykh commented
@Saran440 for me, by default it shows like:
![image](https://user-images.githubusercontent.com/345102/85867899-df3f5280-b7c9-11ea-8ac3-467d729a6bd6.png)
yet if I remove all the entries, it still acts like there are two of those. Probably because it's declared as "default". @pedrobaeza https://github.com/brainbeanapps/timesheet/blob/b893b30b3c3a503bdf17e5e65a758391c8c0eb0c/hr_timesheet_report/wizards/hr_timesheet_report_wizard.py#L56 maybe you have some hints?

2020-06-28 07:23 UTC, alexey-pelykh commented
@Saran440 the issue with grouping/detail fields is resolved, please re-review

2020-06-29 11:02 UTC, Saran440 approved these changes
Functional Test. LGTM :+1:

2020-06-30 06:09 UTC, alexey-pelykh commented
/ocabot merge nobump

2020-06-30 07:01 UTC, merged