[12.0][MIG] hr_timesheet_sheet_attendance
OCA/timesheet pull request #199
Opened 2019-03-04 10:05 UTC by naglis

2019-04-15 10:19 UTC, bizzappdev approved these changes
LGTM

2019-05-20 22:20 UTC, tbaden requested changes
thanks for the work 👍 
I did a code review: just some minor change and some optional if you like.

2019-05-20 22:20 UTC, tbaden commented on hr_timesheet_sheet_attendance/__manifest__.py
> +    "Odoo Community Association (OCA)",
please indent this.

2019-05-20 22:20 UTC, tbaden commented on hr_timesheet_sheet_attendance/__manifest__.py
> +    'auto_install': False,
auto_install is by default false, no need to set it (optional)

2019-05-20 22:20 UTC, tbaden commented on hr_timesheet_sheet_attendance/views/hr_attendance_view.xml
> +    <record model="ir.ui.view" id="hr_attendance_view_filter_inherit">
optional change:
id before model

id pattern:
use original id (hr_attendance_view_filter)

>  prefer naming the inherited view after the original over using a name which follows the guidelines. This eases looking up the original view and other inheritance if they all have the same name.

2019-05-20 22:20 UTC, tbaden commented on hr_timesheet_sheet_attendance/views/hr_attendance_view.xml
> +    <record id="view_attendance_tree_inherit" model="ir.ui.view">
optional change:
id before model

id pattern:
use original id (view_attendance_tree)

> prefer naming the inherited view after the original over using a name which follows the guidelines. This eases looking up the original view and other inheritance if they all have the same name.

2019-05-20 22:20 UTC, tbaden commented on hr_timesheet_sheet_attendance/views/hr_timesheet_sheet_view.xml
> +    <record id="hr_timesheet_sheet_inherit_form_simplified" model="ir.ui.view">
optional change:
id before model

id pattern:
use original id (hr_timesheet_sheet_form)

> prefer naming the inherited view after the original over using a name which follows the guidelines. This eases looking up the original view and other inheritance if they all have the same name.

2019-05-20 22:20 UTC, tbaden commented on hr_timesheet_sheet_attendance/views/hr_timesheet_sheet_view.xml
> +    <record id="action_hr_timeseet_sheet_attendance" model="ir.actions.act_window">
optional:
id pattern

> For an action: the main action respects <model_name>_action. Others are suffixed with _<detail>, where detail is an underscore lowercase string explaining the action (should not be long). This is used only if multiple actions are declared for the model.

2019-05-20 22:20 UTC, tbaden commented on hr_timesheet_sheet_attendance/views/hr_timesheet_sheet_view.xml
> +    <record id="action_hr_timeseet_sheet_analytic_line" model="ir.actions.act_window">
optional:
id pattern

> For an action: the main action respects <model_name>_action. Others are suffixed with _<detail>, where detail is an underscore lowercase string explaining the action (should not be long). This is used only if multiple actions are declared for the model.

2020-06-01 06:59 UTC, treviser commented
What is the actual status of this PR?

2020-06-05 21:31 UTC, rafaelbn approved these changes
:+1 Thanksgiving

2020-06-08 12:48 UTC, chienandalu approved these changes
LGTM :+1: Thanks!

2020-06-09 05:23 UTC, chienandalu commented
@tbaden Can you give your final blessing?

2020-06-12 10:27 UTC, tbaden commented
LGTM

2020-06-12 10:27 UTC, tbaden approved these changes

2020-06-12 10:33 UTC, pedrobaeza commented
/ocabot merge nobump

2020-06-12 11:22 UTC, merged