[FIX] hr_timesheet_sheet: fix tests
OCA/timesheet pull request #228
Opened 2019-03-29 11:59 UTC by cubells

As timesheets are merged by position as you can see here:

https://github.com/OCA/hr-timesheet/blob/11.0/hr_timesheet_sheet/models/account_analytic_line.py#L97

It's necessary not to create a timesheet in tests without name the last one, because then, sometimes the tests fail because we are unlinking the last one that is checked later in test, here:

https://github.com/OCA/hr-timesheet/blob/11.0/hr_timesheet_sheet/tests/test_hr_timesheet_sheet.py#L411 

cc @Tecnativa

2019-03-29 13:01 UTC, victor-ditay approved these changes

2019-03-29 15:17 UTC, pedrobaeza approved these changes

2019-03-29 15:32 UTC, mreficent commented
But you are not "fixing" the test, because the test "sometimes" is correct. You should fix the model code to assure the test never fails or fix the test maintaining the way the test was intended. We should be able to test properly the case when the last one is the one without name.

2019-03-29 15:33 UTC, pedrobaeza commented
@mreficent yes, it's fixing the failing tests assuring data integrity. The problem is not in the code, but in absent data that is not present here and set by others.

2019-03-29 15:34 UTC, MiquelRForgeFlow requested changes
Your fix is just avoiding the error that sometimes happens, but not solving the real cause of the issue.

2019-03-29 15:35 UTC, pedrobaeza commented
Please read my last comment. See other similar case here: https://github.com/OCA/sale-workflow/commit/e1016362f91f12461a57c5c375d1c56dfe0bf755#diff-31ba36fbb2f208debac4a8e4cb15fd50

2019-03-29 15:36 UTC, mreficent commented
> The problem is not in the code, but in absent data that is not present here and set by others

set by who and where?

2019-03-29 15:38 UTC, pedrobaeza commented
@mreficent please don't make it more complicated. @cubells has dedicated 8 hours to debug this. It's due to the interaction of other modules that add account.analytic.line, but I can't say right now. If you have it clear the problem, you can suggest a better patch, but for now, I don't see a better one.

2019-03-29 15:57 UTC, mreficent commented
I think the problem is here https://github.com/OCA/hr-timesheet/blob/11.0/hr_timesheet_sheet/tests/test_hr_timesheet_sheet.py#L409. Just delete this line (`sheet._onchange_timesheets()`) and the tests should never fail. So not needed the other changes. If a problem arises again, please show traceback ;)

2019-03-29 15:59 UTC, pedrobaeza commented
Thanks for the insights. I don't have the details, as it was my colleague who made the investigation. He'll report back on Monday.

2019-03-29 16:08 UTC, mreficent commented
In fact, in addition of deleting that line, I found an issue that you could also fix here:

Before this line https://github.com/OCA/hr-timesheet/blob/12.0/hr_timesheet_sheet/models/hr_timesheet_sheet.py#L603 (`new_ts.write({'unit_amount': unit_amount})`), you should add a `new_ts = new_ts.exists()` 🙂

2019-03-29 16:32 UTC, mreficent commented
And also before the `return` (in https://github.com/OCA/hr-timesheet/blob/11.0/hr_timesheet_sheet/models/hr_timesheet_sheet.py#L579), please add `new_ts.unlink()` 😅

2019-03-29 16:33 UTC, pedrobaeza commented
Maybe it's better that you make another PR? :pray:

2019-03-29 16:42 UTC, mreficent commented
Ok, sorry. You are right. I was speculating by just reading code. Just try https://github.com/OCA/hr-timesheet/pull/228#issuecomment-478051862. The other things I am seeing I will test first in local, and will do PR if appropriate.

2019-03-29 16:43 UTC, pedrobaeza commented
OK, thanks. This is going to be the OCA module with more patches in the history!

2019-04-01 07:28 UTC, astirpe approved these changes
I tried this patch locally, on a database where the test was failing. With this patch the tests ran smoothly. Thanks!

2019-04-01 07:30 UTC, pedrobaeza commented
@cubells / @astirpe can you try the proposed fix by @mreficent in your failing database to see if it works better than this one? If not, we'll merge this.

2019-04-01 07:39 UTC, astirpe commented
I first tried by [deleting this line](https://github.com/OCA/hr-timesheet/blob/11.0/hr_timesheet_sheet/tests/test_hr_timesheet_sheet.py#L409) but it didn't solve the issue in my local database instance. Then I tried the proposed fix of this PR and it went well.

2019-04-01 07:49 UTC, pedrobaeza commented
OK, let's merge it for now. @mreficent if you discover other solution that is on the code, not on the tests, please propose the patch.

2019-04-01 07:49 UTC, merged

2019-04-01 07:50 UTC, cubells commented
Changing line proposed by @mreficent doesn't solve the problem and It's needed to run the onchange.

By removing the line you are changing the pupose of the tests.

2019-04-01 07:51 UTC, mreficent commented
ok! :)

2019-04-01 08:24 UTC, alexey-pelykh commented
Does this needs to be ported to v12 as well?