[WIP][12.0][ADD] hr_timesheet_sheet_activity
OCA/timesheet pull request #317
Opened 2020-02-08 13:11 UTC by alexey-pelykh

Addresses #298 by adding activities

2020-02-12 20:27 UTC, sweenya approved these changes
Functional test

2020-02-15 06:39 UTC, artemsenko approved these changes
Functional tests

2020-02-15 13:18 UTC, alexey-pelykh commented
@MiquelRForgeFlow @astirpe this module allows a more advanced activity planning to be used with `mail_activity_reminder` module to ensure noone forgets doing their part of the story :D If possible, please review it's features

2020-02-17 09:27 UTC, astirpe requested changes

2020-02-17 09:27 UTC, astirpe commented on hr_timesheet_sheet_activity/models/hr_timesheet_sheet.py
> +                })
Could just be like this?

```python
                activity.sudo(activity.user_id).write({
                    'user_id': sheet.user_id.id,
                })
```

2020-02-17 09:27 UTC, astirpe commented on hr_timesheet_sheet_activity/models/hr_timesheet_sheet.py
> +            activity.action_feedback()
```python
activity.sudo(activity.user_id).action_feedback()
```

2020-02-17 09:27 UTC, astirpe commented on hr_timesheet_sheet_activity/__manifest__.py
> +        'resource',
Dependency with `resource` is implicitly satisfied

2020-02-17 14:45 UTC, alexey-pelykh commented on hr_timesheet_sheet_activity/models/hr_timesheet_sheet.py
> +                })
It can yet it would be confusing? I was even thinking of making all sudo() to avoid impersonating anyone

2020-02-17 14:45 UTC, alexey-pelykh commented on hr_timesheet_sheet_activity/models/hr_timesheet_sheet.py
> +            activity.action_feedback()
Same here, not sure I want to impersonate?

2020-02-17 14:49 UTC, alexey-pelykh commented on hr_timesheet_sheet_activity/models/hr_timesheet_sheet.py
> +            activity.action_feedback()
hmm, but I'm doing that anyhow...

2020-02-17 14:51 UTC, alexey-pelykh commented on hr_timesheet_sheet_activity/models/hr_timesheet_sheet.py
> +                })
So, what are possible options here:
1) always do as Odoo Bot
2) always do as "current activity assignee" (does that make sense in this case?)
3) what I did

like, if user self-completes or self-assigns the activity, it's ok to act as him/her. Yet when other user (and with timesheet sheets is very much possible) does the action, I didn't want to impersonate assignee, but separate that as "Odoo Bot did"

2020-02-17 14:55 UTC, alexey-pelykh commented on hr_timesheet_sheet_activity/__manifest__.py
> +        'resource',
Done

2020-02-17 15:15 UTC, alexey-pelykh commented on hr_timesheet_sheet_activity/models/hr_timesheet_sheet.py
> +                })
so, that's my reasoning :D

2020-02-19 07:36 UTC, astirpe commented on hr_timesheet_sheet_activity/models/hr_timesheet_sheet.py
> +                })
Ok, makes sense

2020-02-19 12:48 UTC, alexey-pelykh commented on hr_timesheet_sheet_activity/models/hr_timesheet_sheet.py
> +                })
Eligible for approve? :)

2020-02-19 13:55 UTC, astirpe approved these changes
Code review only. Not tested

2020-03-20 07:54 UTC, alexey-pelykh commented
/ocabot merge

2020-03-20 08:37 UTC, merged

2020-04-02 07:10 UTC, CasVissers commented
@alexey-pelykh 
The module is missing dependencies for policy modules:
`AttributeError: 'hr_timesheet.sheet' object has no attribute '_get_possible_reviewers'`

2020-04-02 07:12 UTC, alexey-pelykh commented
@CasVissers does not need to, `_get_possible_reviewers` is declared in `hr_timesheet_sheet` https://github.com/OCA/timesheet/blob/057e75f3c93d0a4562e4cc7bc2228b7416e2c4a2/hr_timesheet_sheet/models/hr_timesheet_sheet.py#L345

2020-04-02 07:14 UTC, CasVissers commented
Aah, think I need to update the module. Stupid, sorry.

2020-04-02 14:50 UTC, CasVissers commented
@alexey-pelykh 
```
  File "/opt/odoo-test/odoo-test-server/odoo/fields.py", line 1067, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo-test/customer/community/hr_timesheet_sheet/models/hr_timesheet_sheet.py", line 207, in _compute_name
    period_end,
TypeError: not all arguments converted during string formatting
```

I think there is an error in:
```
          if sheet.date_end <= sheet.date_start + relativedelta(weekday=SU):
                sheet.name = _('Week %s') % (
                    period_end,
                )
```

2020-04-02 15:51 UTC, alexey-pelykh commented
@CasVissers check your locale, it's likely to have that string translated correctly

2020-04-02 15:53 UTC, alexey-pelykh commented
https://github.com/OCA/timesheet/blob/12.0/hr_timesheet_sheet/i18n/nl.po#L1084
https://github.com/OCA/timesheet/blob/12.0/hr_timesheet_sheet/i18n/nl_BE.po#L988

2020-04-02 15:53 UTC, alexey-pelykh commented
like this

2020-04-03 05:39 UTC, CasVissers commented
Fixed all the Dutch translation errors. Thnx!

2020-04-03 05:51 UTC, CasVissers commented
@alexey-pelykh 
I kept getting the error also in English, fixed it by changing code to:
`            if sheet.date_end <= sheet.date_start + relativedelta(weekday=SU):
                sheet.name = _('Week %s' % period_end)

            else:
                sheet.name = _('Weeks %s - %s' % (
                    period_start,
                    period_end
                ))
`

2020-04-03 07:18 UTC, alexey-pelykh commented
that's not correct, sir, absolutely

2020-04-03 07:32 UTC, alexey-pelykh commented
https://github.com/OCA/timesheet/pull/341 is as close as we can get to fixing that