[13.0][MIG] hr_timesheet_sheet
OCA/timesheet pull request #342
Opened 2020-04-06 10:30 UTC by MiquelRForgeFlow

Supersedes https://github.com/OCA/timesheet/pull/337.

In the tests, I applied the server-side formview utility.

And also I squashed .pot file and number version update automatically generated commits.

2020-04-06 10:37 UTC, alexey-pelykh commented
@MiquelRForgeFlow shouldn't it first be a isort/black/prettier and then migration according to https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch ?

2020-04-06 10:44 UTC, MiquelRForgeFlow commented
Yes, and that's the order implemented. It's just that github show commits ordered by commit creation date instead of correct commit order.

You can check by loading this in local and doing "git log -5", which it will show:

```
...
[FIX] hr_timesheet_sheet: drop fuzzy+python-format translations
[IMP] : black, isort
[MIG] hr_timesheet_sheet: Migration to 13.0
[IMP] hr_timesheet_sheet: black, isort, prettier
[MIG] hr_timesheet_sheet: Migration to 13.0 (complete)
```

2020-04-06 10:46 UTC, alexey-pelykh commented
Hmm, github shows different history for some reason

2020-04-06 10:51 UTC, MiquelRForgeFlow commented
I can edit the date of the commits to make it look how it should, but I thing it's not a good thing, and also I don't care. We should live with it, and hope someday github change their order of showing the commits.

2020-04-06 10:52 UTC, alexey-pelykh commented
Fine with me as it is as long in `git log` it's correct :)

2020-04-06 11:00 UTC, astirpe requested changes

2020-04-06 11:00 UTC, astirpe commented on hr_timesheet_sheet/security/hr_timesheet_sheet_security.xml
> +            >['|',('company_id','=',False),('company_id','in',[company_ids])]</field>
```suggestion
            >['|',('company_id','=',False),('company_id','in',company_ids)]</field>
```

2020-04-06 11:20 UTC, astirpe approved these changes

2020-04-06 11:37 UTC, alexey-pelykh approved these changes
Feels many commits due to multiple migration attempts (by different authors) are not needed, but I just support the effort :)

2020-04-06 18:30 UTC, MiquelRForgeFlow commented
I don't understand why travis ci becomes hidden.

2020-04-06 19:57 UTC, MiquelRForgeFlow commented
It's green :green_apple:

2020-04-07 06:35 UTC, AdriaGForgeFlow approved these changes
Code review :+1:

2020-04-07 09:47 UTC, AaronHForgeFlow approved these changes
:+1: Functional test on local

2020-04-07 09:48 UTC, alexey-pelykh commented
/ocabot merge

2020-04-07 10:14 UTC, merged