[13.0][MIG] hr_timesheet_activity_begin_end: Migration to 13.0
OCA/timesheet pull request #344
Opened 2020-04-10 06:16 UTC by davejames

2020-04-14 13:32 UTC, alexey-pelykh approved these changes

2020-07-14 06:54 UTC, astirpe requested changes
Please cherry-pick https://github.com/OCA/timesheet/pull/307/commits/bfa417eeecba68c129044baeeda0b0104bb3c52b from https://github.com/OCA/timesheet/pull/307

2020-07-25 08:11 UTC, davejames commented
@astirpe I have re-done this migration and your changes are now included

2020-07-27 11:27 UTC, davejames commented
@pedrobaeza any chance you could review this?

2020-07-27 11:28 UTC, pedrobaeza commented
@astirpe should approve your latest changes.

2020-07-27 11:39 UTC, astirpe requested changes

2020-07-27 11:39 UTC, astirpe commented on hr_timesheet_activity_begin_end/models/account_analytic_line.py
> +        self.ensure_one()
Here self could be a recordset, not necessarily a singleton.
This constraint should be rewritten this way:

```python
    @api.constrains("time_start", "time_stop", "unit_amount")
    def _check_time_start_stop(self):
        for line in self:
            value_to_html = self.env["ir.qweb.field.float_time"].value_to_html
            start = timedelta(hours=line.time_start)
            stop = timedelta(hours=line.time_stop)
            ....
            etc..
            ....
```

2020-07-27 11:39 UTC, astirpe commented on hr_timesheet_activity_begin_end/__manifest__.py
>      "author": "Camptocamp, " "Tecnativa, " "Odoo Community Association (OCA)",
```suggestion
    "author": "Camptocamp, Tecnativa, Odoo Community Association (OCA)",
```

2020-07-27 11:56 UTC, astirpe commented on hr_timesheet_activity_begin_end/models/account_analytic_line.py
> +        self.ensure_one()
You forgot the loop on self

2020-07-27 12:07 UTC, astirpe commented on hr_timesheet_activity_begin_end/models/account_analytic_line.py
> +                        for other in (line + others).sorted(lambda l: l.time_start)
Now variable `other` is not used. Please check

2020-07-27 12:31 UTC, astirpe approved these changes
Code LGTM. Not tested.

2020-07-27 12:32 UTC, pedrobaeza commented
/ocabot merge nobump

2020-07-27 12:32 UTC, davejames commented
> Code LGTM. Not tested.

thanks for your review and patience :)

2020-07-27 12:59 UTC, merged