[12.0] [ADD] hr_timesheet_time_type: Ability to add time type in timesheet lines.
OCA/timesheet pull request #356
Opened 2020-06-04 11:16 UTC by Chandresh-SerpentCS

- Project / Configuration menu option, to configure "Time Type" **(For example, "Internal Meeting", "Design", "Development", "Tests")**
- On Timesheet lines, "Time Type" column

2020-06-04 11:23 UTC, alexey-pelykh commented
It seems highly similar to what have been discussed here https://github.com/OCA/timesheet/issues/354 - is that related? cc @dreispt

2020-06-04 11:38 UTC, Chandresh-SerpentCS commented
@alexey-pelykh Yes, It is the solution for #354.

2020-06-04 11:42 UTC, Chandresh-SerpentCS commented
@dreispt I would like to request you for reviewing this PR.

2020-06-07 08:32 UTC, alexey-pelykh requested changes

2020-06-07 08:32 UTC, alexey-pelykh commented on hr_timesheet_time_type/__manifest__.py
> +    "depends": ["hr_timesheet", "project"],
`hr_timesheet` already depends on `project`, no need to specify

2020-06-08 17:20 UTC, dreispt approved these changes
LGTM, code review

2020-06-08 17:21 UTC, dreispt commented on hr_timesheet_time_type/__manifest__.py
> +    "depends": ["hr_timesheet", "project"],
```suggestion
    "depends": ["hr_timesheet"],
```

2020-06-12 13:30 UTC, dreispt commented
@alexey-pelykh Your comments were addressed.

2020-06-12 16:10 UTC, alexey-pelykh approved these changes

2020-06-12 16:54 UTC, dreispt commented
/ocabot merge nobump

2020-06-12 17:44 UTC, merged