[14.0] [mig] hr_ timesheet_sheet
OCA/timesheet pull request #434
Opened 2021-03-09 12:39 UTC by schhatbar

2021-03-09 16:28 UTC, CasVissers-360ERP commented on hr_timesheet_sheet/models/hr_timesheet_sheet.py
> +    name = fields.Char(compute="_compute_name", context_dependent=True)
> context_dependent', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it

2021-03-09 16:28 UTC, CasVissers-360ERP requested changes
Initial feedback

2021-03-11 04:50 UTC, fshah-initos approved these changes
LGTM

2021-03-12 05:02 UTC, fshah-initos approved these changes

2021-03-12 05:04 UTC, schhatbar commented
@CasVissers-360ERP Can you please review this PR? 
Thanks in advance!

2021-03-12 05:09 UTC, CasVissers-360ERP approved these changes

2021-03-12 05:43 UTC, schhatbar commented
@alexey-pelykh Can you please merge this PR hence it is approved?
Thanks in Advance!

2021-03-15 11:23 UTC, schhatbar commented
@pedrobaeza  Can you please merge this PR hence it is approved?
Thanks in Advance!

2021-03-18 14:08 UTC, CasVissers-360ERP commented on hr_timesheet_sheet/models/hr_timesheet_sheet.py
> +            res |= self.env.ref("hr_timesheet.group_timesheet_manager").users
Should be group_hr_timesheet_approver not timesheet_manager?

2021-03-18 14:15 UTC, CasVissers-360ERP commented on hr_timesheet_sheet/models/hr_timesheet_sheet.py
> +                self.message_subscribe(partner_ids=subscribers.ids)
self.message_subscribe(partner_ids=subscribers.ids) should be sheet.message_subscribe(partner_ids=subscribers.ids)

2021-03-23 05:23 UTC, schhatbar-initos commented
@CasVissers-360ERP  The suggested changes has been done. Can you please review this PR Need to get it merged asap because this module is dependent upon many other modules?
Thanks in advance!

2021-03-31 05:26 UTC, schhatbar-initos commented
@pedrobaeza Can you please check with this PR?

2021-03-31 06:17 UTC, pedrobaeza commented on hr_timesheet_sheet/security/ir.model.access.csv
> +access_hr_timesheet_sheet_line,hr_timesheet.sheet.line,model_hr_timesheet_sheet_line,base.group_user,1,1,1,1
Shouldn't this be to the user with timesheet permissions only?

2021-03-31 07:05 UTC, pedrobaeza commented on hr_timesheet_sheet/security/ir.model.access.csv
> +access_hr_timesheet_sheet_line,hr_timesheet.sheet.line,model_hr_timesheet_sheet_line,base.group_user,1,1,1,1
The following line is the same case.

2021-03-31 07:10 UTC, pedrobaeza commented
/ocabot merge nobump

2021-03-31 08:13 UTC, merged