[14.0] [mig] hr_timesheet_task_domain
OCA/timesheet pull request #447
Opened 2021-05-04 11:26 UTC by fshah-initos

2021-06-04 06:16 UTC, dsolanki-initos approved these changes
LGTM. Functional and code review.

2021-06-10 11:34 UTC, fshah-initos commented
@Tardo It would be great if you could add reviews here

2021-06-11 17:05 UTC, Tardo requested changes
Thanks, please check the comments.

2021-06-11 17:05 UTC, Tardo commented on hr_timesheet_task_domain/__manifest__.py
> +    "author": "Tecnativa, " "CorporateHub, " "Odoo Community Association (OCA)",
```suggestion
    "author": "Tecnativa, CorporateHub, Odoo Community Association (OCA)",
```

2021-06-11 17:05 UTC, Tardo commented on hr_timesheet_task_domain/models/account_analytic_line.py
> +        )
See https://github.com/OCA/project/pull/813
```suggestion
```

2021-06-11 17:05 UTC, Tardo commented on hr_timesheet_task_domain/models/account_analytic_line.py
> +                task_domain = task_domain + [("stage_id.is_closed", "=", False)]
```suggestion
            task_domain = [("project_id", "=", self.project_id.id), ("stage_id.is_closed", "=", False)]
```

2021-06-25 06:11 UTC, fshah-initos commented
It would be nice if we get the reviews here

2021-07-02 08:32 UTC, fshah-initos commented
It would be nice if we get the reviews here

2021-07-09 06:21 UTC, fshah-initos commented
It would be nice if we get the reviews here

2021-07-12 07:27 UTC, isserver1 approved these changes
Looks good

2021-07-16 09:50 UTC, fshah-initos commented
Hi @Tardo can you please check the latest changes

2021-07-23 08:49 UTC, fshah-initos commented
It would be nice if we could merge this PR

2021-07-30 12:02 UTC, fshah-initos commented
Is it possible to merge this PR?

2021-08-13 09:03 UTC, FernandoRomera approved these changes

2021-08-13 13:13 UTC, AntoniRomera approved these changes

2021-08-13 13:15 UTC, AntoniRomera commented
@Tardo Can you check the PR?

2021-08-18 14:07 UTC, AntoniRomera commented
Hello @pedrobaeza  

You can make the merge of this PR to be able to continue with the migration of the "project_timsheet_time_control" to be able to make the merge of the modules "helpdesk_timesheet" and "helpdesk_timesheet_time_control" as you have proposed, I have made the PR to be able to have all the options and to see which is preferred, but to make the merge more dependencies are needed.

2021-08-18 14:08 UTC, pedrobaeza commented
/ocabot merge nobump

2021-08-18 14:32 UTC, merged