[15.0][MIG] project_task_stage_allow_timesheet
OCA/timesheet pull request #523
Opened 2022-09-30 10:37 UTC by Freni-OSI

2022-10-21 20:59 UTC, CRogos requested changes

2022-10-21 20:59 UTC, CRogos commented on project_task_stage_allow_timesheet/models/account_analytic_line.py
>                      stage.display_name,
The error message is not displayed correctly and is cut after the word "stage".
Maybe you can also add some unit as well.

2022-10-21 20:59 UTC, CRogos commented on project_task_stage_allow_timesheet/models/account_analytic_line.py
> +            "]"
Shouldn't we create an object and serialize it, instead of concating a string?

2023-03-26 12:26 UTC, closed without merging

2023-03-27 21:51 UTC, rafaelbn commented
@Freni-OSI @dreispt @max3903 are you continuing with this PR?