[14.0][IMP] hr_timesheet_activity_begin_end: missing form fields
OCA/timesheet pull request #577
Opened 2023-03-15 20:38 UTC by dalonsod

`time_start` and `time_stop` fields were missing in timesheets `form` view. This PR adds them.

2023-03-15 20:47 UTC, dalonsod commented
@ernestotejeda @CRogos could you review? Thanks!

2023-03-16 08:19 UTC, CRogos requested changes
The code looks good, but there is similar change in the v16 PR. 
https://github.com/OCA/timesheet/pull/566/commits/b1785effae6139e94415083b33fd58ef3e0d4144
I think we should use the same XML in both versions.

2023-03-16 08:46 UTC, dalonsod commented
Thanks @CRogos , I agree with you...
In v16 migration, could that improvement be placed in a separate commit, so it could be ported to v15?

Meanwhile I'll replicate the code in the same way as yours, but view `name`, that seeems to be wrong.

2023-03-16 09:35 UTC, CRogos commented
Yes you are right. I'll change the name and commit it in a separate commit.

2023-03-16 11:47 UTC, dalonsod commented
> I think we should use the same XML in both versions.

@CRogos applied changes

2023-03-16 20:52 UTC, CRogos requested changes
I am so sorry. I wasn't aware that the date was located diffently in v14.
![image](https://user-images.githubusercontent.com/1799080/225749373-352d0508-5075-43aa-80a0-629667e5836c.png)
That doesn't look good in my opinion. 

The same code in v16 leads to this result.
![image](https://user-images.githubusercontent.com/1799080/225749413-acab9e36-57a8-4d00-b27e-b85c486b49be.png)

So maybe we should switch to your first xml version in v14 and v16?

2023-03-17 16:42 UTC, dalonsod commented
Done!

![imagen](https://user-images.githubusercontent.com/12749832/225966364-b4e3d64c-d658-44d3-bb14-e53bd9af5747.png)

2023-03-20 08:01 UTC, CRogos approved these changes
Code and functional review LGTM

2023-04-17 11:32 UTC, dalonsod commented
@schhatbar-initos @davejames could you review? Thanks!

2023-04-17 11:58 UTC, davejames approved these changes
LGTM

2023-04-17 15:15 UTC, dalonsod commented
@nimarosa is this ready to be merged? Thanks!

2023-04-18 13:31 UTC, nimarosa approved these changes

2023-04-18 13:32 UTC, nimarosa commented
/ocabot merge patch

2023-04-18 13:38 UTC, merged