[17.0][MIG] sale_timesheet_line_exclude
OCA/timesheet pull request #639
Opened 2024-02-23 13:06 UTC by MohamedOsman7

2024-02-28 08:28 UTC, CRogos requested changes
Functional and Code Review LGTM, but the .deb file needs to be removed.

2024-02-28 08:28 UTC, CRogos commented on pandoc-3.1.12.1-1-amd64.deb
Remove this file

2024-02-28 10:15 UTC, CRogos approved these changes

2024-03-06 13:51 UTC, alexey-pelykh approved these changes
Code LGTM

2024-03-18 15:30 UTC, CRogos commented
@alexey-pelykh can you also merge this?

2024-03-18 15:31 UTC, alexey-pelykh commented
/ocabot merge nobump

2024-03-18 15:36 UTC, merged