[17.0][MIG] hr_timesheet_task_required
OCA/timesheet pull request #640
Opened 2024-02-26 15:43 UTC by MohamedOsman7

2024-02-27 09:17 UTC, FrancoMaxime approved these changes
LGTM: code review

2024-02-27 13:36 UTC, MohamedOsman7 commented
I encountered a problem which i will describe step by step with screenshots:
1. In the settings, under the project app settings, i did not set the checkmark in the field (Require Tasks on Timesheets):
<img width="570" alt="2024-02-27 14_07_43-Odoo - Settings und 3 weitere Seiten - Geschäftlich – Microsoft​ Edge" src="https://github.com/OCA/timesheet/assets/126760755/9f42e77c-2f2f-49f3-93c0-4754e1e93eb8">


2. In the project app, i choosed the project "Research & Development" and opened his settings:
<img width="556" alt="2024-02-27 14_08_23-Odoo - Projects und 3 weitere Seiten - Geschäftlich – Microsoft​ Edge" src="https://github.com/OCA/timesheet/assets/126760755/c6b71722-d984-43a3-ab9f-e6a42577de34">


3. I also did not set the checkmark in the field (Require Tasks on Timesheets):
<img width="756" alt="2024-02-27 14_09_28-Odoo - Research   Development und 3 weitere Seiten - Geschäftlich – Microsoft​ E" src="https://github.com/OCA/timesheet/assets/126760755/4b87c5ca-e5ae-4d8f-aa6d-430eb0a7795a">


4. In the timesheet app, when attempting to create a timesheet entry with the same project **without choosing a task**, i encountered an unexpected error:
<img width="1270" alt="2024-02-27 14_10_56-Odoo - My Timesheets und 3 weitere Seiten - Geschäftlich – Microsoft​ Edge" src="https://github.com/OCA/timesheet/assets/126760755/f8968789-0e92-412a-b88b-0ecadaca9974">


**Apart from the fact that the error occurs at all, where it should not occur, the error message does not match the error specified in the code, which is:**

**(Note: This screenshot is from version 16.0)**

<img width="485" alt="2024-02-27 13_39_08-Odoo - My Timesheets und 7 weitere Seiten - Profil 2 – Microsoft​ Edge" src="https://github.com/OCA/timesheet/assets/126760755/a933e20f-da73-4172-8144-fb3de2318470">

I would assume that something has changed in the new odoo standard in this regard. But i did not find anything **yet**. Any ideas?

2024-02-28 08:19 UTC, CRogos requested changes
Tested and working, but some code improvements possible.

2024-02-28 08:19 UTC, CRogos commented on hr_timesheet_task_required/views/res_config_settings.xml
> +                expr="//app[@data-string='Project']//block[@name='project_time']"
`expr="//block[@name='project_time']"`

should be sufficient.

2024-02-28 08:19 UTC, CRogos commented on hr_timesheet_task_required/views/project_project.xml
>                          <field name="is_timesheet_task_required" class="oe_inline" />
I think this should be replaced by this:

```
                    <setting id="timesheet_task_settings" help="Set tasks on timesheet as a mandatory field" invisible="allow_timesheets == False">
                        <field name="is_timesheet_task_required"/>
                    </setting>
```

2024-02-28 08:19 UTC, CRogos commented on hr_timesheet_task_required/views/account_analytic_line.xml
> +                <attribute name="required">is_task_required == True
` <attribute name="required">is_task_required</attribute>`
should be enough.

2024-02-28 08:19 UTC, CRogos commented on hr_timesheet_task_required/views/account_analytic_line.xml
> +                <attribute name="required">is_task_required == True
Same here. remove "== True"

2024-02-28 08:19 UTC, CRogos commented on hr_timesheet_task_required/views/account_analytic_line.xml
>                  <field name="is_task_required" invisible="1" />
invisible needs to be changed to 
`column_invisible="True"`

2024-02-28 10:21 UTC, CRogos approved these changes

2024-02-28 12:38 UTC, dreispt commented
/ocabot migration hr_timesheet_task_required

2024-03-02 16:07 UTC, dreispt commented
/ocabot merge nobump

2024-03-02 16:11 UTC, merged