[MIG] Port hr_timesheet_task to 9.0
OCA/timesheet pull request #83
Opened 2016-09-23 08:46 UTC by PierreFaniel

Migrate the module hr_timesheet_task to Odoo v9.
Addition of tasks in timesheet report

2016-09-23 09:02 UTC, pedrobaeza commented
Hi, Pierre, thanks for the contribution. I have checked the CLA received.

2016-12-13 13:58 UTC, pedrobaeza requested changes

2016-12-13 13:58 UTC, pedrobaeza commented on hr_timesheet_task/__init__.py
> +# Copyright 2016 Niboo SPRL, Camptocamp SA
You should add a line per each author

2016-12-13 13:58 UTC, pedrobaeza commented on hr_timesheet_task/__openerp__.py
> +    The user is now able to select a task in a timesheet
Extract this to a README.rst and fill the complete template like https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2016-12-13 14:15 UTC, rafaelbn commented on hr_timesheet_task/__openerp__.py
> +    The user is now able to select a task in a timesheet
Please @PierreFaniel take care of this issue when writing README https://github.com/OCA/hr-timesheet/issues/54 and thanks for this contribution!

2016-12-13 14:22 UTC, pedrobaeza commented on hr_timesheet_task/__openerp__.py
> +    The user is now able to select a task in a timesheet
timesheet_task module can be removed now in v9.

2016-12-13 14:47 UTC, pedrobaeza commented on hr_timesheet_task/static/description/index.html
>          <div class="oe_span12">
Now that you have put README.rst, you can remove this file.

2016-12-13 17:09 UTC, Garamotte commented on hr_timesheet_task/models/hr_timesheet_report.py
> +    task_id = fields.Many2one('project.task', 'Task', readonly=True)
Please explicitely name all arguments (`comodel_name` and `string`)

2016-12-13 17:09 UTC, Garamotte commented on hr_timesheet_task/views/hr_timesheet_view.xml
> +    <data>
Replace `<openerp>` by `<odoo>` and remove the `<data>` tag.

2016-12-16 01:56 UTC, rafaelbn commented
Runbot fails, I cannot test it: skipped state in https://runbot.odoo-community.org/runbot/repo/github-com-oca-hr-timesheet-117

2017-01-27 12:32 UTC, PierreFaniel commented
Hello,

I would like to know why runbot skips all the v9 builds for this repo.

Can anybody help with this ?

2017-01-27 12:34 UTC, pedrobaeza commented
It should be because .travis.yml is not according last template: https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml

2017-01-27 14:09 UTC, PierreFaniel commented
This pull request seems to not want to work for me 😄 

Travis fails and in the logs I see
`ParseError: "13 Permission denied" while parsing /home/travis/odoo-9.0/openerp/addons/base/base_data.xml:26`
but I don't understand why. Is this something I caused? Is the .travis.yml wrongly configured?

2017-01-27 14:11 UTC, pedrobaeza commented
I think it's due to https://github.com/odoo/odoo/pull/15248.

2018-03-30 05:23 UTC, feketemihai approved these changes
Not tested

2018-04-27 00:32 UTC, rafaelbn approved these changes
Thanks @PierreFaniel :+1: 

There are still some minor comments that you could quicky attend.

2019-11-13 18:00 UTC, closed without merging